spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_flyway?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: admin

  flyway:
    enabled: true
    locations: classpath:db/migration/mysql

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_SECRET:}
            scope: profile, email

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: beautyapplicationilias@gmail.com
    password: kfna sibw nutu ephb
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}

jwt:
  publicKey: classpath:public-key.pem
  privateKey: classpath:pkcs8.key

aws:
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET_KEY:}

google:
  accessKey: ${GOOGLE_ACCESS_KEY}

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
cors:
  url: http://localhost:4200